/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbc.program;

import java.util.List;
import javax.swing.DefaultListModel;
import jdbc.model.Mahasiswa;
import jdbc.service.MysqlMahasiswaService;

/**
 *
 * @author User
 */
public class JFrameUtama extends javax.swing.JFrame {

    private MysqlMahasiswaService mahasiswaService;

    public JFrameUtama() {
        initComponents();
        mahasiswaService = new MysqlMahasiswaService();
        loadAllMahasiswa();
    }

    private void loadAllMahasiswa() {
        List<Mahasiswa> mahasiswaList = mahasiswaService.getAll();
        DefaultListModel<String> listModelId = new DefaultListModel<>();
        DefaultListModel<String> listModelNama = new DefaultListModel<>();
        for (Mahasiswa mhs : mahasiswaList) {
            listModelId.addElement(String.valueOf(mhs.getId()));
            listModelNama.addElement(mhs.getNama());
        }
        list_id.setModel(listModelId);
        list_nama.setModel(listModelNama);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_semuadata = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        btn_tambahkan = new javax.swing.JButton();
        txt_id_edit = new javax.swing.JTextField();
        txt_id_hapus = new javax.swing.JTextField();
        txt_nama_edit = new javax.swing.JTextField();
        txt_nama_hapus = new javax.swing.JTextField();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_id = new javax.swing.JList<>();
        btn_tambahkan4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_nama = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 32, -1, -1));

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Kelola Data Mahasiswa");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        btn_semuadata.setText("Ambil Semua Data");
        btn_semuadata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_semuadataActionPerformed(evt);
            }
        });
        getContentPane().add(btn_semuadata, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        jLabel4.setText("Nama");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));
        getContentPane().add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 280, -1));

        btn_tambahkan.setText("Tambahkan");
        btn_tambahkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahkanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tambahkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));
        getContentPane().add(txt_id_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 40, 30));
        getContentPane().add(txt_id_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 40, 30));
        getContentPane().add(txt_nama_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 220, 30));
        getContentPane().add(txt_nama_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 220, 30));

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        getContentPane().add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 110, -1));

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 110, 30));

        btn_reset.setText("Reset Indeks");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 140, 30));

        list_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_idMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list_id);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 330));

        btn_tambahkan4.setText("Hapus");
        getContentPane().add(btn_tambahkan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 110, 30));

        jScrollPane2.setViewportView(list_nama);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 100, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void list_idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_idMouseClicked
        int selectedId = Integer.parseInt(list_id.getSelectedValue());
        Mahasiswa mhs = mahasiswaService.getById(selectedId);
        if (mhs != null) {
            txt_id_edit.setText(String.valueOf(mhs.getId()));
            txt_nama_edit.setText(mhs.getNama());
            txt_id_hapus.setText(String.valueOf(mhs.getId()));
            txt_nama_hapus.setText(mhs.getNama());
        }
    }//GEN-LAST:event_list_idMouseClicked

    private void btn_semuadataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_semuadataActionPerformed
        loadAllMahasiswa();
    }//GEN-LAST:event_btn_semuadataActionPerformed

    private void btn_tambahkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahkanActionPerformed
        String nama = txt_nama.getText();
        Mahasiswa mhs = new Mahasiswa('1', nama);
        mahasiswaService.add(mhs);
        loadAllMahasiswa();
    }//GEN-LAST:event_btn_tambahkanActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        int id = Integer.parseInt(txt_id_edit.getText());
        String nama = txt_nama_edit.getText();
        Mahasiswa mhs = new Mahasiswa(id, nama);
        mahasiswaService.update(mhs);
        loadAllMahasiswa();
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        int id = Integer.parseInt(txt_id_hapus.getText());
        mahasiswaService.delete(id);
        loadAllMahasiswa();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        mahasiswaService.indexReset();
        loadAllMahasiswa();
    }//GEN-LAST:event_btn_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_semuadata;
    private javax.swing.JButton btn_tambahkan;
    private javax.swing.JButton btn_tambahkan4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> list_id;
    private javax.swing.JList<String> list_nama;
    private javax.swing.JTextField txt_id_edit;
    private javax.swing.JTextField txt_id_hapus;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nama_edit;
    private javax.swing.JTextField txt_nama_hapus;
    // End of variables declaration//GEN-END:variables
}
