
package guicollection;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;


public class GUI_JList4 extends javax.swing.JFrame {
    
    DefaultListModel<String> dlm;
    List<String> items = new ArrayList<>();
    Set<String> itemSet = new HashSet<>();
    Map<Integer, String> itemMap = new HashMap<>();
    String[] datas = {"Buku", "Meja", "Kursi", "Tas", "Pintu"};

    public GUI_JList4() {
        initComponents();
        setTitle("Java Collection");
        dlm = new DefaultListModel<>();
        jListItem.setModel(dlm);
        
        for (String data : datas) {
            dlm.addElement(data);
            
        }
        updateJumDataTersimpanList();
        updateJumDataTersimpanSet();
        updateJumDataTersimpanMap();
        
        jListItem.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int index = jListItem.getSelectedIndex();
                    if (index != -1) {
                        String selectedValue = jListItem.getSelectedValue();
                        jTextFieldNamaItem.setText(selectedValue);
                    }
                }
            }
        });
    }
    
    private void addItem(String namaItem) {
        dlm.addElement(namaItem);
    }
    
    private void updateJumDataTersimpanList() {
        jLabelJumlahDataList.setText("Data Tersimpan = " + items.size());
    }
    
    private void updateJumDataTersimpanSet() {
        jLabelJumlahDataSet.setText("Data Tersimpan = " + itemSet.size());
    }
    
    private void updateJumDataTersimpanMap() {
        jLabelJumlahDataMap.setText("Data Tersimpan = " + itemMap.size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextFieldNamaItem = new javax.swing.JTextField();
        jLabelJumlahDataSet = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListItem = new javax.swing.JList<>();
        jButtonClearAll = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonAddItem = new javax.swing.JButton();
        jButtonSaveToList = new javax.swing.JButton();
        jLabelNamaItem = new javax.swing.JLabel();
        jButtonInsertDataList = new javax.swing.JButton();
        jButtonSaveToSet = new javax.swing.JButton();
        jButtonInsertDataSet = new javax.swing.JButton();
        jButtonSaveToMap = new javax.swing.JButton();
        jButtonInsertDataMap = new javax.swing.JButton();
        jLabelJumlahDataList = new javax.swing.JLabel();
        jLabelJumlahDataMap = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldNamaItem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldNamaItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 170, 30));

        jLabelJumlahDataSet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(jLabelJumlahDataSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 140, 30));

        jScrollPane2.setViewportView(jListItem);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 330));

        jButtonClearAll.setBackground(new java.awt.Color(255, 0, 0));
        jButtonClearAll.setText("Clear");
        jButtonClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearAllActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonClearAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 160, 30));

        jButtonUpdate.setBackground(new java.awt.Color(204, 255, 153));
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 100, 30));

        jButtonDelete.setBackground(new java.awt.Color(255, 0, 51));
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 100, 30));

        jButtonAddItem.setBackground(new java.awt.Color(204, 255, 204));
        jButtonAddItem.setText("Add");
        jButtonAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddItemActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAddItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 100, 30));

        jButtonSaveToList.setBackground(new java.awt.Color(102, 153, 255));
        jButtonSaveToList.setText("Save to List ->");
        jButtonSaveToList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveToListActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSaveToList, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 130, 30));

        jLabelNamaItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNamaItem.setText("Nama Item : ");
        jPanel2.add(jLabelNamaItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 90, 30));

        jButtonInsertDataList.setBackground(new java.awt.Color(153, 255, 153));
        jButtonInsertDataList.setText("<- Insert Data List");
        jButtonInsertDataList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertDataListActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonInsertDataList, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 130, 30));

        jButtonSaveToSet.setBackground(new java.awt.Color(102, 153, 255));
        jButtonSaveToSet.setText("Save to Set ->");
        jButtonSaveToSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveToSetActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSaveToSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 130, 30));

        jButtonInsertDataSet.setBackground(new java.awt.Color(153, 255, 153));
        jButtonInsertDataSet.setText("<- Insert Data Set");
        jButtonInsertDataSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertDataSetActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonInsertDataSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 130, 30));

        jButtonSaveToMap.setBackground(new java.awt.Color(102, 153, 255));
        jButtonSaveToMap.setText("Save to Map ->");
        jButtonSaveToMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveToMapActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSaveToMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 130, 30));

        jButtonInsertDataMap.setBackground(new java.awt.Color(153, 255, 153));
        jButtonInsertDataMap.setText("<- Insert Data Map");
        jButtonInsertDataMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertDataMapActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonInsertDataMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 130, 30));

        jLabelJumlahDataList.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(jLabelJumlahDataList, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 140, 30));

        jLabelJumlahDataMap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(jLabelJumlahDataMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 140, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearAllActionPerformed
        dlm.clear();
    }//GEN-LAST:event_jButtonClearAllActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        int index = jListItem.getSelectedIndex();
        if (index == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih item yang akan diperbarui.", "No Selection", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String selected = jTextFieldNamaItem.getText();
        dlm.setElementAt(selected, index);
        jTextFieldNamaItem.setText("");
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        int index = jListItem.getSelectedIndex();
        if (index == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih item yang akan dihapus.", "No Selection", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        dlm.removeElementAt(index);
        jTextFieldNamaItem.setText("");
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddItemActionPerformed
        String newItem = jTextFieldNamaItem.getText().trim();
    
        if (newItem.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan masukkan nama item.", "No Item", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        addItem(newItem);
        jTextFieldNamaItem.setText("");
    }//GEN-LAST:event_jButtonAddItemActionPerformed

    private void jButtonSaveToListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveToListActionPerformed
        if(!items.isEmpty()){
            items.clear();
        }
        
        for(int i = 0; i < dlm.getSize(); i++){
            items.add(dlm.getElementAt(i));
        }
        updateJumDataTersimpanList();
    }//GEN-LAST:event_jButtonSaveToListActionPerformed

    private void jButtonInsertDataListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertDataListActionPerformed
        for (String item : items) {
            dlm.addElement(item);
        }
    }//GEN-LAST:event_jButtonInsertDataListActionPerformed

    private void jButtonSaveToSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveToSetActionPerformed
        if (!itemSet.isEmpty()) {
            itemSet.clear();
        }
        
        for (int i = 0; i < dlm.getSize(); i++) {
            itemSet.add(dlm.getElementAt(i));
        }
        updateJumDataTersimpanSet();
    }//GEN-LAST:event_jButtonSaveToSetActionPerformed

    private void jButtonInsertDataSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertDataSetActionPerformed
        for (String item : itemSet) {
            dlm.addElement(item);
        }
    }//GEN-LAST:event_jButtonInsertDataSetActionPerformed

    private void jButtonSaveToMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveToMapActionPerformed
        if (!itemMap.isEmpty()) {
            itemMap.clear();
        }
        
        for (int i = 0; i < dlm.getSize(); i++) {
            itemMap.put(i, dlm.getElementAt(i));
        }
        updateJumDataTersimpanMap();
    }//GEN-LAST:event_jButtonSaveToMapActionPerformed

    private void jButtonInsertDataMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertDataMapActionPerformed
        dlm.clear();
        for (Map.Entry<Integer, String> entry : itemMap.entrySet()) {
            dlm.addElement(entry.getValue());
        }
    }//GEN-LAST:event_jButtonInsertDataMapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_JList4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_JList4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_JList4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_JList4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_JList4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddItem;
    private javax.swing.JButton jButtonClearAll;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonInsertDataList;
    private javax.swing.JButton jButtonInsertDataMap;
    private javax.swing.JButton jButtonInsertDataSet;
    private javax.swing.JButton jButtonSaveToList;
    private javax.swing.JButton jButtonSaveToMap;
    private javax.swing.JButton jButtonSaveToSet;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabelJumlahDataList;
    private javax.swing.JLabel jLabelJumlahDataMap;
    private javax.swing.JLabel jLabelJumlahDataSet;
    private javax.swing.JLabel jLabelNamaItem;
    private javax.swing.JList<String> jListItem;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldNamaItem;
    // End of variables declaration//GEN-END:variables
}
